Set(%Lifecycles,
    service => {
        initial => [qw(new)],
        active => [qw(open stalled), 'waiting for service', 'waiting for customer', 'waiting for engineer', 'waiting for supplier'],
        inactive => [qw(resolved rejected deleted)],
        defaults => {
            on_create => 'new',
            approved  => 'open',
            denied    => 'rejected',
            reminder_on_open     => 'open',
            reminder_on_resolve  => 'resolved',
        },
        transitions => {
            ""       => [qw(new open resolved)],
            # from   => [ to list ],
            new      => [qw(    open stalled resolved rejected deleted), 'waiting for service', 'waiting for customer', 'waiting for engineer', 'waiting for supplier'],
            open     => [qw(new      stalled resolved rejected deleted), 'waiting for service', 'waiting for customer', 'waiting for engineer', 'waiting for supplier'],
            stalled  => [qw(new open         resolved rejected deleted), 'waiting for service', 'waiting for customer', 'waiting for engineer', 'waiting for supplier'],
            resolved => [qw(new open stalled          rejected deleted), 'waiting for service', 'waiting for customer', 'waiting for engineer', 'waiting for supplier'],
            rejected => [qw(new open stalled resolved          deleted), 'waiting for service', 'waiting for customer', 'waiting for engineer', 'waiting for supplier'],
            deleted  => [qw(new open)],
            'waiting for service'  => [qw(open stalled resolved rejected deleted), 'waiting for customer', 'waiting for engineer', 'waiting for supplier'],
            'waiting for customer' => [qw(open stalled resolved rejected deleted), 'waiting for service', 'waiting for engineer', 'waiting for supplier'],
            'waiting for engineer' => [qw(open stalled resolved rejected deleted), 'waiting for customer', 'waiting for service', 'waiting for supplier'],
            'waiting for supplier' => [qw(open stalled resolved rejected deleted), 'waiting for customer', 'waiting for service', 'waiting for engineer'],
        },
        rights => {
            '* -> deleted'  => 'DeleteTicket',
            '* -> *'        => 'ModifyTicket',
        },
        actions => [
            'new -> open'      => { label  => 'Open It', update => 'Respond' },
            'new -> resolved'  => { label  => 'Resolve', update => 'Comment' },
            'new -> rejected'  => { label  => 'Reject',  update => 'Respond' },
            'new -> deleted'   => { label  => 'Delete',                      },
            'open -> stalled'  => { label  => 'Stall',   update => 'Comment' },
            'open -> resolved' => { label  => 'Resolve', update => 'Comment' },
            'open -> rejected' => { label  => 'Reject',  update => 'Respond' },
            'stalled -> open'  => { label  => 'Open It',                     },
            'resolved -> open' => { label  => 'Re-open', update => 'Comment' },
            'rejected -> open' => { label  => 'Re-open', update => 'Comment' },
            'deleted -> open'  => { label  => 'Undelete',                    },
        ],
    },
    supplier => {
        initial => [qw(new)],
        active => [qw(open stalled), 'waiting for service', 'waiting for supplier', 'waiting for engineer'],
        inactive => [qw(resolved rejected deleted)],
        defaults => {
            on_create => 'new',
            approved  => 'open',
            denied    => 'rejected',
            reminder_on_open     => 'open',
            reminder_on_resolve  => 'resolved',
        },
        transitions => {
            ""       => [qw(new open resolved)],
            # from   => [ to list ],
            new      => [qw(    open stalled resolved rejected deleted), 'waiting for service', 'waiting for supplier', 'waiting for engineer'],
            open     => [qw(new      stalled resolved rejected deleted), 'waiting for service', 'waiting for supplier', 'waiting for engineer'],
            stalled  => [qw(new open         resolved rejected deleted), 'waiting for service', 'waiting for supplier', 'waiting for engineer'],
            resolved => [qw(new open stalled          rejected deleted), 'waiting for service', 'waiting for supplier', 'waiting for engineer'],
            rejected => [qw(new open stalled resolved          deleted), 'waiting for service', 'waiting for supplier', 'waiting for engineer'],
            deleted  => [qw(new open stalled resolved rejected        )],
            'waiting for service'  => [qw(open stalled resolved rejected deleted), 'waiting for supplier', 'waiting for engineer'],
            'waiting for supplier' => [qw(open stalled resolved rejected deleted), 'waiting for service', 'waiting for engineer'],
            'waiting for engineer' => [qw(open stalled resolved rejected deleted), 'waiting for service', 'waiting for supplier'],
        },
        rights => {
            '* -> deleted'  => 'DeleteTicket',
            '* -> *'        => 'ModifyTicket',
        },
        actions => [
            'new -> open'      => { label  => 'Open It', update => 'Respond' },
            'new -> resolved'  => { label  => 'Resolve', update => 'Comment' },
            'new -> rejected'  => { label  => 'Reject',  update => 'Respond' },
            'new -> deleted'   => { label  => 'Delete',                      },
            'open -> stalled'  => { label  => 'Stall',   update => 'Comment' },
            'open -> resolved' => { label  => 'Resolve', update => 'Comment' },
            'open -> rejected' => { label  => 'Reject',  update => 'Respond' },
            'stalled -> open'  => { label  => 'Open It',                     },
            'resolved -> open' => { label  => 'Re-open', update => 'Comment' },
            'rejected -> open' => { label  => 'Re-open', update => 'Comment' },
            'deleted -> open'  => { label  => 'Undelete',                    },
        ],
    },
     __maps__ => {
        'service -> default' => {
            'waiting for customer' => 'stalled',
            'waiting for engineer' => 'stalled',
            'waiting for service'  => 'stalled',
        },
        'service -> supplier' => {
            'waiting for customer' => 'waiting for service',
        },
        'supplier -> default' => {
            'waiting for engineer' => 'stalled',
            'waiting for service'  => 'stalled',
            'waiting for supplier' => 'stalled',
        },
        'supplier -> service' => {
            'waiting for supplier' => 'waiting for service',
        },
     }
);
